### ISSUE TITLE
🚀 [New Contribution] : Maven basics explained

### ISSUE THREAD

**Issue by ShubhraSuman** [Showwcase/hacktoberfest#11]
Maven is the most commonly used build tool. Aiming to write an article to publish basics of maven

**Comment by ShubhraSuman** [comment]
Hi @atapas,
Will this not be counted towards hacktoberfest?

**Comment by atapas** [comment]
Yes, it should be. What happen?

**Comment by ShubhraSuman** [comment]
Here it's showing excluded 
![Screenshot_20221010-093814](https://user-images.githubusercontent.com/53232818/194798129-b1ff43ce-4372-4594-a46d-bf681a0343c9.jpg)

**Comment by atapas** [comment]
> Here it's showing excluded ![Screenshot_20221010-093814](https://user-images.githubusercontent.com/53232818/194798129-b1ff43ce-4372-4594-a46d-bf681a0343c9.jpg)

Ok, I see. We will try to seek more information on what happened. There could be some issues with the registration process. Give us a couple of days, we will update you here.

**Comment by ShubhraSuman** [comment]
Sure
