### ISSUE TITLE
🚀 [New Contribution]: Demystifying Hacktoberfest

### ISSUE THREAD

**Issue by Susmita-Dey** [Showwcase/hacktoberfest#18]
**Describe Your Contribution Here**
This is a blog on guide to Markdown files. Markdown files are an important part to write docs for any open source projects.

I want to add it to this repo as part of Showwcase Hacktoberfest contribution.

Show link:- https://www.showwcase.com/show/17620/a-complete-guide-for-markdown-files

**Comment by atapas** [comment]
Sure, are you republishing it?

**Comment by Susmita-Dey** [comment]
> Sure, are you republishing it?

Yes

**Comment by Susmita-Dey** [comment]
Isn't it gonna be valid?

**Comment by atapas** [comment]
> Isn't it gonna be valid?

The ground rule is to publish as a first time original one as show. How about you plan another one?

**Comment by Susmita-Dey** [comment]
Do you mean writing a new blog?

**Comment by atapas** [comment]
> Do you mean writing a new blog?

That's right.

**Comment by Susmita-Dey** [comment]
@atapas So, can I share this: https://www.showwcase.com/show/17617/demystifying-hacktoberfest

**Comment by Susmita-Dey** [comment]
This is the original one. Just posted today morning.

**Comment by atapas** [comment]
Certainly, create a PR

**Comment by Susmita-Dey** [comment]
> Certainly, create a PR

For the Markdown one or [this one](https://www.showwcase.com/show/17617/demystifying-hacktoberfest)?

**Comment by atapas** [comment]
For the one you published today... Check the readme on how to mark your entry.

**Comment by Susmita-Dey** [comment]
> For the one you published today... Check the readme on how to mark your entry.

Okay

**Comment by Susmita-Dey** [comment]
Completed by #19
