### ISSUE TITLE
🚀 [New Contribution]  Creating an email custom scalar to Apollo GraphQL

### ISSUE THREAD

**Issue by kevinmmartins** [Showwcase/hacktoberfest#22]
https://www.showwcase.com/show/17632/creating-an-email-custom-scalar-to-apollo-graphql

How to create a email custom scalar on GraphQL

**Comment by atapas** [comment]
You no longer need to create ISSUE/PR for the low-code and no-code contributions. Please check this communication here and follow the same(especially the ground rules). We will pick the contributions from there. Thanks!

https://www.showwcase.com/opensource
