### ISSUE TITLE
🚀 [New Contribution] 4 dicas para engenheiros elétricos/telecomunicações que estão migrando para desenvolvimento

### ISSUE THREAD

**Issue by kevinmmartins** [Showwcase/hacktoberfest#23]
https://www.showwcase.com/show/17633/4-dicas-para-engenheiros-eletricostelecomunicacoes-que-estao-migrando-para-desenvolvimento

Portuguese article focused on telecommunications engineering migrating to software development

**Comment by atapas** [comment]
You no longer need to create ISSUE/PR for the low-code and no-code contributions. Please check this communication here and follow the same(especially the ground rules). We will pick the contributions from there. Thanks!

https://www.showwcase.com/opensource
