### ISSUE TITLE
🚀 [New Contribution] Convert JAR to bundle in ServiceMix

### ISSUE THREAD

**Issue by kevinmmartins** [Showwcase/hacktoberfest#26]
https://www.showwcase.com/show/17645/convert-jar-to-bundle-in-servicemix

**Comment by atapas** [comment]
You no longer need to create ISSUE/PR for the low-code and no-code contributions. Please check this communication here and follow the same(especially the ground rules). We will pick the contributions from there. Thanks!

https://www.showwcase.com/opensource
