### ISSUE TITLE
🚀 [New Contribution]: Walrus operator in python

### ISSUE THREAD

**Issue by niteshxp** [Showwcase/hacktoberfest#38]
**Describe Your Contribution Here**
Walrus operator is newly introduced concept in python. I'm aiming for a blog article to explain it.

**Comment by atapas** [comment]
@niteshxp You no longer need to create ISSUE/PR for the low-code and no-code contributions. Please check this communication here and follow the same(especially the ground rules). We will pick the contributions from there. Thanks!

https://www.showwcase.com/opensource
