### ISSUE TITLE
Integrate GitHub actions in this repository

### ISSUE THREAD

**Issue by hasnainmakada-99** [Showwcase/hacktoberfest#4]
**Is your feature request related to a problem? Please describe.**

I would like to integrate GitHub actions in this repository to greet new contributors whenever they make their first PR or raise an issue for the first time - As a part of hacktoberfest

**Describe the solution you'd like**

Integrate GitHub actions

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by atapas** [comment]
Sure, do it.
