### ISSUE TITLE
🚀 [New Contribution] : Setup Laravel Project Blog

### ISSUE THREAD

**Issue by JunedSetiawan** [Showwcase/hacktoberfest#41]
**Describe Your Contribution Here**

How To Setup Laravel Project Cloned From Github, clone repo on github to develop laravel project and also can clone repo to be able to contribute with team.

**Comment by atapas** [comment]
You no longer need to create ISSUE/PR for the low-code and no-code contributions. Please check this communication here and follow the same(especially the ground rules). We will pick the contributions from there. Thanks!

https://www.showwcase.com/opensource
