### ISSUE TITLE
🚀 [New Contribution] Hash table visualizer

### ISSUE THREAD

**Issue by Atharane** [Showwcase/hacktoberfest#5]
**A site designed to help learners understand the workings of hash tables. With custom animations for each operation, users can simulate inserting and deleting in a hash table.**

**Comment by ElectricPlant19** [comment]
i can give it aa go

**Comment by Atharane** [comment]
Hey Aditya, glad to hear you're interested in making this website. I did it myself, you can see it at https://atharane.github.io/envisage.github.io/hash.html. I just need my issue assigned to me so that I can submit a pull request

**Comment by atapas** [comment]
Hi @Atharane @ElectricPlant19 

Thanks for putting this one. To understand it better, are you also planning to create a show(content on Showwcase) as a low-code contribution?

Please check the criteria once. You can always build the one you intend to but for low-code contribution theme you need to create a show,article, video, etc and create a PR here.

**Comment by Atharane** [comment]
Yeah I'm gonna write a brief documentation about Hash tables and about my
site as a show on showcase.

**Comment by Atharane** [comment]
Thanks a ton, @atapas

**Comment by ranbir7** [comment]
hey there , can I contribute to this issue?
I'm Just halfway there with python ,If you suggest me some skills required for this project
I would happily try my best acquiring them.
